### ISSUE TITLE
Try/Catch block hides exception that describes additional NLTK setup instructions

### ISSUE THREAD

**Issue by sourcesync** [semi-technologies/Getting-Started-With-Weaviate-Python-Client#1]
The try/catch block in the cell that defines "get_articles_from_newspaper" hides an exception that prints additional NLTK setup instructions.

My python installations is based on Anaconda:
* Python 3.7.10
* Jupyter lab 3.0.11

I added an additional cell containing the following everything worked ok:

!pip install nltk
import nltk
nltk.download('punkt')

**Comment by bobvanluijt** [comment]
Thanks @gosha1128 😊👍

**Comment by StefanBogdan** [comment]
Hi @gosha1128 ,

Thank you for finding this bug. I fixed it and added the changes to the Medium article too.
